from typing import List
from typing_extensions import TypedDict
from langchain_core.documents import Document
from langgraph.graph import END, StateGraph, START



from rag.rag_fusion import retrieval_rag_fusion
from rag.fallback import fallback
from rag.generation import generate_chain
from rag.graders import retrieval_grader, answer_grader, hallucination_grader
from rag.web_search import web_search_tool
from rag.routing import route_question_chain
from core.config import DATA_DIR


class GraphState(TypedDict):
    """
    Represents the shared state of the StudentAI LangGraph workflow.

    The graph state is passed between nodes during graph execution.
    Each node can read values from the state and update the relevant
    fields as the question moves through the retrieval, grading,
    generation, and fallback stages.

    Attributes:
        question (str):
            The original question submitted by the user.

        generation (str):
            The answer generated by the language model.

        documents (List[str]):
            A list of documents retrieved from the vector store
            and used as context for generating the answer.
    """
    '''
    Graph State
    '''
    question: str
    generation: str
    documents: List[str]

"""
====================================================
Nodes
"""


def make_retrieve_node(retriever):
    retrieval_chain = retrieval_rag_fusion(retriever)  

    def retrieve(state):
        """
        Retrieve relevant documents for the user's question.

        Args:
            state (GraphState):
                Current state of the LangGraph workflow.

        Returns:
            dict:
                Updated graph state containing the retrieved
                documents and original question.
        """
        print("---Retrieving...---")
        question = state["question"]
        documents = retrieval_chain.invoke({"question": question})
        return {"documents": documents, "question": question}

    return retrieve

def llm_fallback(state):
    """
    Generate an answer using the fallback language model.

    This node is used when the primary RAG workflow cannot
    provide a suitable answer. Instead of relying on retrieved
    documents, the fallback model answers using its general
    knowledge.

    Args:
        state (GraphState):
            Current state of the LangGraph workflow.

    Returns:
        dict:
            Updated graph state containing the generated answer
            and original question.
    """
    print("---Fallback...---")
    question = state["question"]
    generation = fallback().invoke({"question": question})
    return {"question": question, "generation": generation}

def generate(state):
    """
    Generate an answer using the retrieved documents.

    This node performs the main RAG generation step. It provides
    the user's question and retrieved documents to the generation
    chain so that the language model can produce a
    document-grounded answer.

    Args:
        state (GraphState):
            Current state containing the user's question and
            retrieved documents.

    Returns:
        dict:
            Updated graph state containing the generated answer,
            question, and retrieved documents.
    """
    print("---Generating...---")
    question = state["question"]
    documents = state["documents"]
    if not isinstance(documents, list):
        documents = [documents]
        
    generated_output = generate_chain().invoke({"question": question, "documents": documents})
    return {"question": question, "generation": generated_output, "documents": documents}


def grade_documents(state):
    """
    Evaluate the relevance of retrieved documents.

    Each retrieved document is passed through the retrieval
    grader to determine whether it is relevant to the user's
    question.

    Documents graded as relevant are retained, while irrelevant
    documents are removed from the graph state.

    Args:
        state (GraphState):
            Current state containing the user's question and
            retrieved documents.

    Returns:
        dict:
            Updated graph state containing only relevant documents
            and the original question.
    """
    print("---Checking document relevance...---")
    question = state["question"]
    documents = state["documents"]

    if not isinstance(documents, list):
        documents = [documents]

    filtered_docs = []
    for d in documents:
        score = retrieval_grader().invoke({"question": question, "document": d})
        grade = score.is_relevant
        if grade == "yes":
            print("---GRADE: Document relevant---")
            filtered_docs.append(d)
        else:
            print("---GRADE: Document not relevant---")
            continue
    return {"documents": filtered_docs, "question": question}

def web_search(state):
    """
    Search the web for additional information about the user's
    question.

    This node is used when the retrieved documents are insufficient
    or when the graph determines that external information is
    required.

    The web search results are converted into LangChain Document
    objects so they can be processed in the same way as documents
    retrieved from the vector store.

    Args:
        state (GraphState):
            Current state containing the user's question.

    Returns:
        dict:
            Updated graph state containing web search documents
            and the original question.
    """

    print("---Web Searching...---")
    question = state["question"]

    docs = web_search_tool.invoke({"query": question}) 
    web_search_doc = []
    for d in docs["results"]:
        doc = Document(page_content=str(d["content"]),
                        metadata={
                            "source":d["url"]
                        })
        web_search_doc.append(doc)
        
    return { "documents": web_search_doc, "question": question}


"""
=============================================================
Edges
"""

def route_question(state):
    """
    Determine which data source should be used to answer the
    user's question.

    The routing LLM decides whether the question should be handled
    using the vector store (RAG) or an external web search.

    If the routing model does not return a valid tool call, the
    question is routed to the fallback LLM.

    Args:
        state (GraphState):
            Current state of the LangGraph workflow containing
            the user's question.

    Returns:
        str:
            Name of the next LangGraph node to execute.
            Possible values are:
                - "llm_fallback"
                - "web_search"
                - "vectorstore"
    """
    print("---Routing question...---")
    question = state["question"]
    source = route_question_chain().invoke({"question": question})

    if "tool_calls" not in source.additional_kwargs:
        print("---Route question to fallback---")
        return "llm_fallback"
    if len(source.additional_kwargs["tool_calls"]) == 0:
        raise "Route could no decide source"

    datasource = source.additional_kwargs["tool_calls"][0]["function"]["name"]
    if datasource == "web_search":
        print("---Route question to web search---")
        return "web_search"
    elif datasource == "vectorstore":
        print("---Route question to RAG---")
        return "vectorstore"
    else:
        print('f{datasource}: Route undefined, route to web search---')
        return "web_search"



def decide_to_generate(state):
    """
    Decide whether the system should generate an answer using
    the retrieved documents or perform a web search.

    This function is used after document relevance grading.
    If at least one relevant document remains, the workflow
    proceeds to answer generation. Otherwise, it searches the web
    for additional information.

    Args:
        state (GraphState):
            Current state containing the filtered documents.

    Returns:
        str:
            Name of the next LangGraph node:
                - "generate" if relevant documents exist.
                - "web_search" if no relevant documents exist.
    """
    print("---Decide to generate---")
    filtered_documents = state["documents"]

    if not filtered_documents:
        print("---No related document, do web search---")
        return "web_search"
    else:

        print("---Document related, generate---")
        return "generate"


def check_hallucination_and_utility(state):
    """
    Evaluate whether the generated answer is both grounded in
    the retrieved documents and useful for answering the question.

    The function performs two checks:

        1. Hallucination check:
           Determines whether the generated answer is supported
           by the retrieved documents.

        2. Utility check:
           Determines whether the generated answer actually
           addresses the user's question.

    The result determines whether the answer should be accepted,
    regenerated, or followed by another web search.

    Args:
        state (GraphState):
            Current state containing the question, retrieved
            documents, and generated answer.

    Returns:
        str:
            Routing decision for the next LangGraph node:
                - "useful" if the answer is grounded and answers
                  the question.
                - "not useful" if the answer is grounded but does
                  not adequately answer the question.
                - "not supported" if the answer is not grounded
                  in the retrieved documents.
    """
    print("---Check hallucination and utility---")
    question = state["question"]
    document = state["documents"]
    generation = state["generation"]

    check_hallucination = hallucination_grader().invoke({"document": document, "generation": generation})
    is_grounded = check_hallucination.is_grounded

    if is_grounded == "yes":
        print("---Generation is grounded---")
        print("---Check utility---")
        check_utility = answer_grader().invoke({"question": question, "generation": generation})
        has_answered = check_utility.has_answered
        if has_answered == "yes":
            print("---Generation addresses question---")
            return "useful"
        else:
            print("---Generation not useful, web search again---")
            return "not useful"
    else:
        print("---Generation is not grounded in documents, regeneration---")
        return "not supported"

"""
=====================================================================
Build Graph
"""

def build_graph(retriever, checkpointer):
    """
    Build and compile the StudentAI LangGraph workflow.

    This function defines the graph structure by registering all
    processing nodes, connecting them with normal edges, and
    defining conditional edges that determine the next step based
    on the current graph state.

    The workflow supports:

        1. Question routing
        2. Vector store retrieval
        3. Document relevance grading
        4. Web search fallback
        5. Answer generation
        6. Hallucination checking
        7. Answer utility checking
        8. LLM fallback
        9. Conversation state persistence through a checkpointer

    Args:
        retriever:
            Retriever used by the vector store retrieval node
            to search for relevant documents.

        checkpointer:
            LangGraph checkpointer used to persist graph state
            between requests and conversation sessions.

    Returns:
        CompiledStateGraph:
            A compiled LangGraph workflow ready to process
            user questions.
    """
    workflow = StateGraph(GraphState)
    workflow.add_node("web_search", web_search)
    retrival_node = make_retrieve_node(retriever)
    workflow.add_node("retrieve", retrival_node)
    workflow.add_node("grade_document", grade_documents)
    workflow.add_node("generate", generate)
    workflow.add_node("llm_fallback", llm_fallback)

    workflow.add_conditional_edges(
        START, 
        route_question,
        {
            "web_search": "web_search",
            "vectorstore": "retrieve",
            "llm_fallback": "llm_fallback",
        },
    )

    workflow.add_edge("web_search", "grade_document")
    workflow.add_edge("retrieve", "grade_document")
    workflow.add_edge("llm_fallback", END)

    workflow.add_conditional_edges(
        "grade_document",
        decide_to_generate,
        {
            "web_search": "web_search",
            "generate": "generate",
        },
    )

    workflow.add_conditional_edges(
        "generate",
        check_hallucination_and_utility,
        {
            "useful": END,
            "not useful": "web_search",
            "not supported": "generate",
        },
    )

 
    return workflow.compile(checkpointer=checkpointer)


    

